### ISSUE TITLE
最新版本的mp分页查询不兼容了，

### ISSUE THREAD

**Issue by CiicDong** [unbright/mplus-helper#2]

**Comment by CiicDong** [comment]
![image](https://user-images.githubusercontent.com/20351235/121170488-df741900-c887-11eb-928b-669811538082.png)
这个方法在最新版本里面被删除了，不晓得要引用哪个

**Comment by CiicDong** [comment]
![image](https://user-images.githubusercontent.com/20351235/121170564-f7e43380-c887-11eb-9602-9c5eed1e5aa1.png)

**Comment by CiicDong** [comment]
![image](https://user-images.githubusercontent.com/20351235/121170634-0df1f400-c888-11eb-8c3d-4b6c4b409851.png)

**Comment by CiicDong** [comment]
这个方法被删除了， 不知道要用哪个合适呢

**Comment by unbright** [comment]
多谢提醒，这个方法被删了，已经升到到最新版本
